name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create SSH key file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > my_ssh_key
          chmod 600 my_ssh_key

      - name: Sync files to VPS using rsync
        run: |
          rsync -avz --exclude=.git --exclude=node_modules --exclude=build -e 'ssh -i my_ssh_key -o StrictHostKeyChecking=no' ./ root@46.202.155.206:/var/www/ihale360

      - name: Install dependencies and build frontend
        run: |
          ssh -i my_ssh_key -o StrictHostKeyChecking=no root@46.202.155.206 << 'EOF'
            cd /var/www/ihale360/client
            npm ci
            npm run build
          EOF

      - name: Restart Nginx and PM2
        run: |
          ssh -i my_ssh_key -o StrictHostKeyChecking=no root@46.202.155.206 << 'EOF'
            sudo systemctl restart nginx
            pm2 reload all --update-env
            pm2 save
          EOF

      - name: Remove SSH key file
        if: always()
        run: rm -f my_ssh_key
